### ISSUE TITLE
Default initialization of const object requires a user-provided default constructor

### ISSUE THREAD

**Issue by flanggut** [simonfuhrmann/mve#232]
The changes introduced in 718924b8fbc70f9521df074f0cb650284acb45ed remove the user-defined constructor of mvs::Settings wich causes an error when compiling UMVE with Clang. 

`viewinspect/imageoperations.cc:39:25: error: default initialization of an
      object of const type 'const mvs::Settings' without a user-provided
      default constructor`

The C standard requires the following
> If a program calls for the default initialization of an object of a const-qualified type T, T shall be a class type with a user-provided default constructor.

GCC does not implement that rule, Clang does. Possible solutions would be to not declare the settings as const or add an explicit default constructor
```C 
struct A
{
     A();
     int i = 1;
};
inline A::A() = default;
```

See also:
[1] http://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
[2] http://stackoverflow.com/questions/21900237/do-i-really-need-to-implement-user-provided-constructor-for-const-objects
[3] http://stackoverflow.com/questions/26077807/why-does-gcc-allow-a-const-object-without-a-user-declared-default-constructor-bu

**Comment by simonfuhrmann** [comment]
Can you prepare a CL where you just drop the const?

**Comment by flanggut** [comment]
see #233
